
baseURL = "https://bio.drrscuba.com"
languageCode = "en-us"
title = "Dive Rinse Repeat Scuba, LLC"
theme = "bootstrap-bp-hugo-startpage"
copyright = "Dive Rinse Repeat Scuba, LLC"
canonifyURLs = true
enableGitInfo = true

[markup.goldmark.renderer]
  unsafe = true
  
# ############################# Default Parameters ##########################

[params]
  description = "Dive Rinse Repeat Scuba"
  #images = ["logo.jpg"]
  startPageColumns = false
  #welcomeText = "We love SCUBA! Our staff of PADI certified professionals can take you from Open Water Scuba Diver to Master Scuba Diver, and everything in between!"
  logo = "img/DRR-Logo-white-medium.png"
