baseURL = "https://drrscuba.com"
languageCode = "en-us"
title = "Dive Rinse Repeat Scuba, LLC"
canonifyURLs = true
enableGitInfo = true

# # post pagination
# paginate = "6"
# # post excerpt
# summaryLength = "15"
# # disqus short name
# disqusShortname = "" 
# get your shortname form here : https://disqus.com

# ############################# Navigation ##################################
[[menu.main]]
name = "About Us"
URL = "/about"
weight = 1

# [[menu.main]]
# name = "Service"
# URL = "services"
# weight = 2

# [[menu.main]]
# name = "Portfolio"
# URL = "portfolio"
# weight = 3

# [[menu.main]]
# name = "Team"
# URL = "team"
# weight = 4

# [[menu.main]]
# name = "Pricing"
# URL = "pricing"
# weight = 5

# [[menu.main]]
# name = "Blog"
# URL = "blog"
# weight = 6

# [[menu.main]]
# name = "Contact"
# URL = "contact"
# weight = 7



# ############################# Default Parameters ##########################
[params]
logo = "img/DRR-Logo-white-medium.png"
# # Meta data
# description = "Responsive Multipurpose Parallax HTML5 Template"
# author = "Themefisher"
# # Google Analitycs
# google_analitycs_id = "" # Your ID
# # post share
# post_share = true

# # preloader
# [params.preloader]
# enable = true
# preloader = "images/logo.png"

# # google map
# [params.map]
# enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png"

# ############################# social icons ##########################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"

[[params.contact]]
URL = "mailto:info@drrscuba.com"
Name = "info@drrscuba.com"
Icon = "envelope"

[[params.contact]]
URL = "tel:+18168384440"
Name = "(816) 838-4440"
Icon = "phone"